### ISSUE TITLE
 What is the difference to other leaflet-R packages?

### ISSUE THREAD

**Issue by Make42** [chgrl/leafletR#18]
There exist (at least) two other R-packages for leaflet:

https://github.com/rstudio
https://github.com/jcheng5/leaflet-shiny

What is the difference to this package, and when and why should I use which one?

**Comment by chgrl** [comment]
Well, which package to use depends on the way you want to create maps.

leafletR provides an "standard R-like" coding style. There are functions for data conversion, styling and map creation and you use one after the other to make a map.

Rstudio/leaflet has something like a modular step-by-step philosophy, using a pipe operator to manipulate several map parameters.

Just have a look at the package examples, to see what I mean:

leafletR:
```
library(leafletR)

# load example data (Fiji Earthquakes)
data(quakes)

# store data in GeoJSON file (just a subset here)
q.dat <- toGeoJSON(data=quakes[1:99,], dest=tempdir(), name="quakes")

# make style based on quake magnitude
q.style <- styleGrad(prop="mag", breaks=seq(4, 6.5, by=0.5), 
  style.val=rev(heat.colors(5)), leg="Richter Magnitude", 
  fill.alpha=0.7, rad=8)

# create map
q.map <- leaflet(data=q.dat, dest=tempdir(), title="Fiji Earthquakes", 
  base.map="mqsat", style=q.style, popup="mag")

# view map in browser
q.map
```

rstudio/leaflet:
```
library(leaflet)
m = leaflet() %>% addTiles()
m  # a map with the default OSM tile layer

m = m %>% setView(-93.65, 42.0285, zoom = 17)
m

m %>% addPopups(-93.65, 42.0285, 'Here is the <b>Department of Statistics</b>, ISU')
```

Finally rstudio/leaflet-shiny is a bit special here, since it "only" produces shiny apps. You may also use rstudio/leaflet to create a shiny app, but its shiny support is currently very limited. leafletR does not support shiny at all.

To make it short: If you like it the old school R way, you may choose leafletR. If you like it flexible, try rstudio/leaflet. If you want to make an R-shiny app, use rstudio/leaflet-shiny.

Please note: I never used rstudio/leaflet and rstudio/leaflet-shiny. I did not even know of their existence when I published leafletR. So just try out yourself. :-)

**Comment by Make42** [comment]
Thank you very much for the answer. Where is a (good) documentation for leafletR to be found?

**Comment by chgrl** [comment]
I know, I know - even a short tutorial would be better than the package manual (see http://cran.r-project.org/web/packages/leafletR/leafletR.pdf for the full manual btw). Well, I think it is not too bad, as I added lots of examples. Time will come, when I write the planned vignette...I hope so...
