### ISSUE TITLE
styleGrad with mutliple layers

### ISSUE THREAD

**Issue by jhollist** [chgrl/leafletR#23]
Appears to be a bug when trying to style one layer as graduated and one as single symbol (may exist for categories too, but I haven't tried that).  Looks like the function that get's written to the html for the graduated symbol doesn't get output correctly.  It is getting wrapped up as if it were JSON.

To repeat the problem:

```
data(quakes)
qks <- toGeoJSON(data=quakes, dest=tempdir())
qks2 <- toGeoJSON(data=quakes, dest=tempdir())
sty <- styleGrad(prop="mag", breaks=seq(4, 6.5, by=0.5), 
                 style.val=rev(heat.colors(5)), leg="Richter Magnitude")
sty2 <- styleSingle(col="red")
map <- leaflet(data=list(qks,qks2), dest=tempdir(), 
               title="Fiji Earthquakes", style=list(sty,sty2))
```

I may try to track this down myself and if I do will submit a PR.  But thought you might want to know.

**Comment by chgrl** [comment]
Hi Jeffrey,

This is not a bug but a missing feature. leafletR does not yet support layers with graduated or categorized style in combination with other layers.

The problem here is rather the legend than the combination of layers, which should easy be done. In my opinion a multi-layer map or a map with a graduated/categorized style without a legend is worthless. Therefore, before leafletR supports multiple style types, one have to think about a new legend concept where several (types of) legends are combined (and that could be hidden maybe, because of the space such a legend might need). 

The template legend.brew is a mess and I'm planning a rewrite of it anyway. The new legend concept would best be done together with this rewrite. Feel free to try on your own, but beware of the code you find in legend.brew ;-). If you are fit in Leaflet and/or Javascript, a show/hide mechanism for the legend would be of great help in the first step.

Cheers
Christian

**Comment by jhollist** [comment]
Thanks for gettin back to me, @chgrl !

I did start working on this and have the multiple styles working, but then quickly noticed the legend issue.  For my current need this works as we are adding the legends in manually.  I agree that  the two go hand in hand and you would need both in production.

I am not yet experienced with Leaflet or Javascript, I'm mostly and R guy.  This is actually my first time playing with Leaflet.  If I get some time, I may take a stab, but can't make any promises.

Again thanks for your work on this.  I has helped me out with my current project.  As this is a bigger issue and an enhancement, I'll close the issue to keep things clean.

Cheers!
Jeff
